name: EzHomes
version: ${project.version}
main: lol.hyper.ezhomes.EzHomes
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/ezhomes.82663/
description: A super easy to use homes plugin.
commands:
  sethome:
    usage: /sethome <name>
    permission: ezhomes.sethome
  home:
    usage: /home <name>
    permission: ezhomes.home
  homes:
    usage: /homes
    permission: ezhomes.homes
  updatehome:
    usage: /updatehome <home>
    permission: ezhomes.updatehome
  delhome:
    usage: /delhome <home>
    permission: ezhomes.delhome
  where:
    usage: /where <home>
    permission: ezhomes.where
  respawnhome:
    usage: /respawnhome <home>
    permission: ezhomes.respawnhome
  ezhomes:
    usage: /ezhomes
    permission: ezhomes.command
permissions:
  ezhomes.reload:
    default: op
    description: Allows the usage of /ezhomes reload.
  ezhomes.bypasslimit:
    default: op
    description: Allows player to bypass home limit.
  ezhomes.bypasscooldown:
    default: op
    description: Allows player to bypass cooldown between teleports.
  ezhomes.command:
    default: op
    description: Allows the usage of /ezhomes.
  ezhomes.sethome:
    default: true
    description: Allows the usage of /sethome.
  ezhomes.home:
    default: true
    description: Allows the usage of /home.
  ezhomes.homes:
    default: true
    description: Allows the usage of /homes.
  ezhomes.updatehome:
    default: true
    description: Allows the usage of /updatehome.
  ezhomes.delhome:
    default: true
    description: Allows the usage of /delhome.
  ezhomes.where:
    default: true
    description: Allows the usage of /where.
  ezhomes.respawnhome:
    default: true
    description: Allows the usage of /respawnhome.